[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@openzeppelin/contracts=lib/v3-periphery-foundry/node_modules/@openzeppelin/contracts']


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
