[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@uniswap/v3-core=lib/v3-core']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
